server:
    port: 19001
spring:
    datasource:
        happy:
            url: jdbc:mysql://112.74.169.195:3306/happy_charge_line?characterEncoding=utf-8
            driverClassName: com.mysql.cj.jdbc.Driver
            username: root
            password: zjxdqh.123
            #        initialize: true
        collect:
            url: jdbc:mysql://112.74.169.195:3306/collect?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true
            driverClassName: com.mysql.cj.jdbc.Driver
            username: root
            password: zjxdqh.123
    mybatis:
        mapper:
            package: com.zjxdqh.happchargeserver.mapper


    redis:
        host: 120.77.33.248
        port: 6379
        password: