server:
    port: 19001
spring:
    datasource:
#        运营库连接配置
        happy:
            url: jdbc:mysql://172.18.91.8:3306/happy_charge_line?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: root
            password: zjxdqh.123
#            采集库连接配置
        collect:
            url: jdbc:mysql://rm-wz9py9x4q6t7et7j9.mysql.rds.aliyuncs.com:3306/collect?useUnicode=true&characterEncoding=UTF-8
            driverClassName: com.mysql.jdbc.Driver
            username: zjxdqhmms
            password: 3186f555ff941f6d!QAZ@WSX
            initialize: true
    mybatis:
        mapper:
            package: com.zjxdqh.happchargeserver.mapper

    redis:
        #        database: 1
        host: 172.18.91.8
        port: 6379
        password: zjxdqh@888